unbind r
bind r source-file ~/mydotfile/tmux/.config/tmux/tmux.conf 

set -ga terminal-overrides ',*:UTF-8'

set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g prefix C-a
set -g mouse on
set -g status-interval 3
set -g set-clipboard on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-window-option -g mode-keys vi 
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "pbcopy"
unbind -T copy-mode-vi MouseDragEnd1Pane

bind % split-window -v -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 85% \
  -h 85%

bind C-g display-popup \
  -d "#{pane_current_path}" \
  -w 85% \
  -h 85% \
  -E "lazygit"

bind C-d display-popup \
  -d "#{pane_current_path}" \
  -w 85% \
  -h 85% \
  -E "lazydocker"

set-option -g status-position top
set -g history-limit 1000000
set -g renumber-windows on
 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'  
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_current_number_color "#{@thm_green}"
set -g @catppuccin_window_text ""
set -g @catppuccin_window_number "#[bold]#W ###I "
set -g @catppuccin_window_current_text ""
set -g @catppuccin_window_current_number "#[bold]#W ###I "
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"

set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg}] #[none]"
set -g @catppuccin_window_middle_separator "#[bg=#{@catppuccin_window_text_color},fg=#{@catppuccin_window_number_color}]"
set -g @catppuccin_window_current_middle_separator "#[bg=#{@catppuccin_window_current_text_color},fg=#{@catppuccin_window_current_number_color}]"

run '~/mydotfile/tmux/.config/tmux/plugins/tpm/tpm'

set -g window-status-separator ""
set -g status-left-length 0
set -g status-left " #[fg=#{@thm_fg} bold]SESSION: (#S) "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold]NORMAL }}"
set -g status-right ""
