source = ~/.config/omarchy/current/theme/hyprlock.conf
 
general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 2
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 
    dots_spacing = 0.35     
    dots_center = true
    outer_color = $outer_color
    inner_color = $inner_color
    font_color = $outer_color
    fade_on_empty = false
    rounding = -1
    check_color = $outer_color
    placeholder_text = <i><span foreground="##cdd6f4">Password...</span></i>
    hide_input = false
    position = 0, -200
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = false
}

label {
    monitor =
    text = Hi there, $USER
    color = $outer_color
    font_size = 25
    font_family = JetBrainsMono Nerd Font Mono

    position = 0, -130
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = $outer_color
  font_size = 26
  font_family = JetBrainsMono Nerd Font Mono
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = $outer_color
  font_size = 95
  font_family = JetBrainsMono Nerd Font Mono
  position = 0, 200
  halign = center
  valign = center
}

# image {
#     monitor =
#     path = /mnt/72B23EA0B23E692D/PHOTO/guts smile.jpeg
#     size = 100
#     border_size = 2
#     # border_color = $foreground
#     position = 0, -50
#     halign = center
#     valign = center
# }
